// Service Worker — Auto-generated by build.js
// Cache version: 1782751487090
const CACHE_VERSION = 'hafis-fyi-v1782751487090';

const CORE_ASSETS = [
    './',
    './index.html',
    './styles.css',
    './manifest.json',
    'https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css',
    'https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/themes/prism-tomorrow.min.css'
];

// Article fragments — cached on first access (runtime caching)
const ARTICLE_ASSETS = [
    './articles/forensics-case-study-02.html',
        './articles/igbt-desat-forensics.html',
        './articles/mechanical-electrodynamics-01.html',
        './articles/mechanical-electrodynamics-02.html',
        './articles/mechanical-electrodynamics-03.html',
        './articles/mock-note.html',
        './articles/power-elec-industry-synth-01.html',
        './articles/vintage-patents-01.html'
];

self.addEventListener('install', event => {
    event.waitUntil(
        caches.open(CACHE_VERSION).then(cache => cache.addAll(CORE_ASSETS))
    );
    self.skipWaiting();
});

self.addEventListener('activate', event => {
    event.waitUntil(
        caches.keys().then(keys =>
            Promise.all(keys.filter(k => k !== CACHE_VERSION).map(k => caches.delete(k)))
        )
    );
    self.clients.claim();
});

self.addEventListener('fetch', event => {
    // Skip non-GET requests (e.g. contact form POST)
    if (event.request.method !== 'GET') return;

    event.respondWith(
        caches.match(event.request).then(cached => {
            if (cached) return cached;

            return fetch(event.request).then(response => {
                if (response.status === 200) {
                    const url = new URL(event.request.url);
                    const shouldCache = url.pathname.includes('/articles/') ||
                                        url.pathname.endsWith('.css') ||
                                        url.pathname.endsWith('.js') ||
                                        url.origin !== self.location.origin;

                    if (shouldCache) {
                        const clone = response.clone();
                        caches.open(CACHE_VERSION).then(cache => cache.put(event.request, clone));
                    }
                }
                return response;
            });
        }).catch(() => {
            // Offline fallback: serve cached index for navigation requests
            if (event.request.mode === 'navigate') {
                return caches.match('./index.html');
            }
        })
    );
});
